### ISSUE TITLE
binary dependent variable

### ISSUE THREAD

**Issue by Isabella725** [Isabella725/stats_2_finalproject#3]
@AaronGullickson  As I am preparing my lab notebook, I have realized that I have a binary dependent variable (people either answer yes or no to having children in their household). 

I am trying to use the models in the dichotomous outcomes slides but I have no idea what the glm results are telling me. I also tried using the relevel command but can't tell if it worked. 

And I am realizing that everything in my data set is binary. I don't feel like I understand how to interpret this or use models for this type of data. I have been reading the dichotomous outcome slides but they are not helping me make sense of this.

**Comment by AaronGullickson** [comment]
@Isabella725 The regression slopes are the log odds ratios of having children in the household. So if the number for a "climate change believer", for example, was -0.075, climate changing believers are about 7% less likely (exp(-.075)=-0.93)) to have children in the household than climate change non-believers, controlling for whatever else is in the model. 

Since all of you independent variables are binary, then its a straighforward to convert to odds ratios that basically just like the cross-products we did way back in the first term when we looked at two-way tables - with the added benefit of being able to control for stuff.

**Comment by Isabella725** [comment]
@AaronGullickson , okay thanks, I guess I'm still confused if I need to be using the GLM code versus the regular lm code? I seem to be getting different results

**Comment by AaronGullickson** [comment]
@Isabella725 Definitely the `glm` command with the argument `family=binomial` included. It should definitely give you different results because you are predicting the log odds of having children at home rather than the linear probability model.

**Comment by Isabella725** [comment]
@AaronGullickson Hi I am trying to knit my pdf (so that I can try to fix any display errors that come up before I then write some more analysis and submit)
I have received this error:

Show in New WindowClear OutputExpand/Collapse Output

\begin{table}
\begin{center}
\begin{tabular}{l c c c }
\hline
 & Model 1 & Model 2 & Model 3 \\
\hline
Intercept                  & $-0.64^{***}$ & $-0.58^{**}$ & $-0.48^{*}$ \\
                           & $(0.16)$      & $(0.20)$     & $(0.21)$    \\
Climate Change Belief(yes) & $0.05$        & $-0.05$      & $-0.03$     \\
                           & $(0.17)$      & $(0.18)$     & $(0.18)$    \\
Natural Causes             &               & $-0.32$      & $-0.27$     \\
                           &               & $(0.21)$     & $(0.21)$    \\
Equal Causes               &               & $0.14$       & $0.16$      \\
                           &               & $(0.14)$     & $(0.14)$    \\
Male                       &               &              & $-0.29^{*}$ \\
                           &               &              & $(0.13)$    \\
\hline
AIC                        & 1496.77       & 1487.53      & 1459.25     \\
BIC                        & 1506.86       & 1507.69      & 1484.36     \\
Log Likelihood             & -746.39       & -739.77      & -724.63     \\
Deviance                   & 1492.77       & 1479.53      & 1449.25     \\
Num. obs.                  & 1148          & 1141         & 1122        \\
\hline
\multicolumn{4}{l}{\scriptsize{$^{***}p<0.001$, $^{**}p<0.01$, $^*p<0.05$}}
\end{tabular}
\caption{Models}
\label{table:coefficients}
\end{center}
\end{table}
Modify Chunk OptionsRun Current Chunk
Show in New WindowClear OutputExpand/Collapse Output



ConsoleC:/Users/Isabella/Desktop/soc312/stats_2_finalproject/analysis/
Console
Terminal

R Markdown

	.../paper/main.Rmd		
Error in yaml::yaml.load(..., eval.expr = TRUE) : 
  Parser error: while parsing a block mapping at line 1, column 1 did not find expected key at line 17, column 1
Calls: <Anonymous> ... parse_yaml_front_matter -> yaml_load -> <Anonymous>
Execution halted

R will not knit for me
